# Basic settings
from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = false
generate_mono_repository_package_tags = false
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = true
pre_bump_hooks = ["printf {{version}} > VERSION"]
post_bump_hooks = []

tag_prefix = "v"

[commit_types]
# Conform to  https://keepachangelog.com/en/1.1.0/
#  - Added for new features.
#  - Changed for changes in existing functionality.
#  - Deprecated for soon-to-be removed features.
#  - Removed for now removed features.
#  - Fixed for any bug fixes.
#  - Security in case of vulnerabilities.
feat = { changelog_title = "Added" }
fix = { changelog_title = "Fixed" }
revert = { changelog_title = "Removed" }
docs = { changelog_title = "Changed" }

deps = { changelog_title = "Security", bump_patch = true } # Specific case of build
hotfix = { changelog_title = "Fixed" }

build = { changelog_title = "", omit_from_changelog = true }
chore = { changelog_title = "", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }
test = { changelog_title = "", omit_from_changelog = true }
style = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "mono"
owner = "demula"
authors = [
  { signature = "34266+demula@users.noreply.github.com", username = "demula" },
]

[bump_profiles]

[packages]
